import { useEffect, useState } from "react";
import type { ServiceCallLifecycleView, WorkReport, WorkReportPartCategory } from "@amarok-one/types";
import { Button } from "@amarok-one/ui";
import { getWorkReportRequest, listWorkReportPartsRequest, updateWorkReportRequest } from "../lib/work-reports-api";

export function WorkReportManagerPanel({ organizationId, serviceCallId, accessToken, lifecycle }: { organizationId: string; serviceCallId: string; accessToken: string; lifecycle: ServiceCallLifecycleView | null }) {
  const [report, setReport] = useState<WorkReport | null>(null); const [catalog, setCatalog] = useState<WorkReportPartCategory[]>([]); const [description, setDescription] = useState(""); const [items, setItems] = useState<{ partId: string; quantity: number }[]>([]); const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const visit = lifecycle?.visits.at(-1);
  useEffect(() => { if (!open || !visit) return; void Promise.all([getWorkReportRequest(organizationId, serviceCallId, visit.id, accessToken), listWorkReportPartsRequest(organizationId, accessToken)]).then(([r, c]) => { setReport(r); setCatalog(c); setDescription(r.workDescription); setItems(r.parts.map(i => ({ partId: i.partId, quantity: i.quantity }))); }); }, [open, visit, organizationId, serviceCallId, accessToken]);
  function quantity(partId: string, delta: number) { setItems(current => { const found = current.find(i => i.partId === partId); if (!found && delta > 0) return [...current, { partId, quantity: 1 }]; if (!found) return current; const next = Math.max(0, found.quantity + delta); return next ? current.map(i => i.partId === partId ? { ...i, quantity: next } : i) : current.filter(i => i.partId !== partId); }); }
  async function save() { if (!report) return; setBusy(true); try { const next = await updateWorkReportRequest(organizationId, report.id, accessToken, { workDescription: description, customerRepresentative: report.customerRepresentative, customerRepresentativeRole: report.customerRepresentativeRole, signatureStrokes: report.signatureStrokes, parts: items }); setReport(next); } finally { setBusy(false); } }
  if (!visit) return null;
  return <section className="customer-detail-card customer-detail-card--wide"><div className="customer-detail-card__header"><div><h3>דוח עבודה</h3><p className="customer-detail-notes">דוח טכנאי ניתן לעריכה לאחר ביקורת מנהל.</p></div><div className="customers-page__actions"><a href="/administration/work-report-parts">ניהול קטלוג חלקים</a><Button variant="secondary" onClick={() => setOpen(value => !value)}>{open ? "סגור" : "פתח דוח עבודה"}</Button></div></div>{open && report ? <div className="customer-detail-list"><p><strong>{report.reportNumber}</strong> · נוצר {new Date(report.createdAt).toLocaleString("he-IL")}</p><label>פירוט העבודה<textarea value={description} onChange={e => setDescription(e.target.value)} rows={6}/></label><h4>חלקים</h4>{catalog.map(category => <div key={category.id}><strong>{category.name}</strong>{category.parts.map(part => <div key={part.id} className="customers-page__actions"><span>{part.name} {part.partNumber ? `(${part.partNumber})` : ""}</span><Button variant="secondary" onClick={() => quantity(part.id, -1)}>−</Button><span>{items.find(i => i.partId === part.id)?.quantity ?? 0}</span><Button variant="secondary" onClick={() => quantity(part.id, 1)}>+</Button></div>)}</div>)}<h4>אישור לקוח</h4><p>{report.customerRepresentative ?? "לא נרשם נציג"}{report.signedAt ? ` · נחתם ${new Date(report.signedAt).toLocaleString("he-IL")}` : " · ללא חתימה"}</p><h4>מדיה</h4>{report.media.length ? report.media.map(media => <p key={media.id}>{media.mediaType === "video" ? "סרטון" : "תמונה"}: {media.fileName}</p>) : <p>לא צורפה מדיה.</p>}<Button variant="primary" disabled={busy} onClick={() => void save()}>{busy ? "שומר…" : "שמירת שינויים"}</Button></div> : null}</section>;
}
