import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import * as ImagePicker from "expo-image-picker";
import { useEffect, useMemo, useRef, useState } from "react";
import { Alert, Image, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View, type GestureResponderEvent } from "react-native";
import type { WorkReport, WorkReportPartCategory } from "@amarok-one/types";
import { useAuth } from "../auth/AuthContext";
import { Button, Card, Eyebrow, ScreenTitle } from "../components/ui";
import { colors, spacing } from "../theme";
import type { RootStackParamList } from "../navigation/types";
import { getWorkReport, listWorkReportParts, saveWorkReport, uploadWorkReportMedia } from "../api/work-reports";
import { isApiRequestError } from "../api/client";

type Props = NativeStackScreenProps<RootStackParamList, "WorkReport">;
type Item = { partId: string; quantity: number };

export function WorkReportScreen({ route }: Props) {
  const { serviceCallId, visitId, title } = route.params; const { user, accessToken } = useAuth();
  const [report, setReport] = useState<WorkReport | null>(null); const [catalog, setCatalog] = useState<WorkReportPartCategory[]>([]);
  const [description, setDescription] = useState(""); const [representative, setRepresentative] = useState(""); const [role, setRole] = useState(""); const [items, setItems] = useState<Item[]>([]); const [signature, setSignature] = useState<number[][][]>([]); const [media, setMedia] = useState<{ uri: string; type: "image" | "video"; name: string; mimeType: string }[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const draftStroke = useRef<number[][]>([]);
  useEffect(() => { if (!user || !accessToken) return; void Promise.all([getWorkReport(user.organization.id, serviceCallId, visitId, accessToken), listWorkReportParts(user.organization.id, accessToken)]).then(([r, c]) => { setReport(r); setCatalog(c); setDescription(r.workDescription); setRepresentative(r.customerRepresentative ?? ""); setRole(r.customerRepresentativeRole ?? ""); setItems(r.parts.map(item => ({ partId: item.partId, quantity: item.quantity }))); setSignature(r.signatureStrokes ?? []); }).catch(e => setError(isApiRequestError(e) ? e.message : "לא ניתן לטעון דוח עבודה")); }, [user, accessToken, serviceCallId, visitId]);
  const selected = useMemo(() => new Map(items.map(x => [x.partId, x.quantity])), [items]);
  function changePart(partId: string, delta: number) { setItems(current => { const found = current.find(x => x.partId === partId); if (!found && delta > 0) return [...current, { partId, quantity: 1 }]; if (!found) return current; const quantity = Math.max(0, found.quantity + delta); return quantity ? current.map(x => x.partId === partId ? { ...x, quantity } : x) : current.filter(x => x.partId !== partId); }); }
  function point(e: GestureResponderEvent) { const p = [Math.round(e.nativeEvent.locationX), Math.round(e.nativeEvent.locationY)]; draftStroke.current.push(p); }
  function finishStroke() { if (draftStroke.current.length > 1) setSignature(s => [...s, draftStroke.current]); draftStroke.current = []; }
  async function addMedia() { const p = await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!p.granted) return setError("נדרשת הרשאה לתמונות ולסרטונים."); const r = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ["images", "videos"], quality: 0.7 }); const a = r.assets?.[0]; if (!r.canceled && a?.uri) setMedia(x => [...x, { uri: a.uri, type: a.type === "video" ? "video" : "image", name: a.fileName ?? `media-${Date.now()}`, mimeType: a.mimeType ?? (a.type === "video" ? "video/mp4" : "image/jpeg") }]); }
  async function save() { if (!user || !accessToken || !report) return; if (!description.trim()) return setError("יש למלא פירוט עבודה."); setBusy(true); setError(null); try { const next = await saveWorkReport(user.organization.id, report.id, accessToken, { workDescription: description, customerRepresentative: representative || undefined, customerRepresentativeRole: role || undefined, signatureStrokes: signature.length ? signature : undefined, parts: items }); for (const file of media) await uploadWorkReportMedia(user.organization.id, report.id, accessToken, file.uri, file.name, file.mimeType); setReport(next); setMedia([]); Alert.alert("נשמר", `דוח ${next.reportNumber} נשמר ומופיע למנהל.`); } catch (e) { setError(isApiRequestError(e) ? e.message : "לא ניתן לשמור את הדוח"); } finally { setBusy(false); } }
  if (!report) return <View style={styles.center}><Text>{error ?? "טוען דוח עבודה…"}</Text></View>;
  return <ScrollView contentContainerStyle={styles.content}><Eyebrow>דוח עבודה · {report.reportNumber}</Eyebrow><ScreenTitle>{title}</ScreenTitle>{error ? <Text style={styles.error}>{error}</Text> : null}
    <Card><Text style={styles.title}>פירוט העבודה *</Text><TextInput multiline value={description} onChangeText={setDescription} style={styles.input} placeholder="תאר את התקלה, העבודה שבוצעה והפעולה הבאה…" placeholderTextColor={colors.textMuted}/></Card>
    <Card><Text style={styles.title}>חלקים</Text><Text style={styles.hint}>בחר חלקים וכמות. אפשר להשאיר ריק.</Text>{catalog.length === 0 ? <Text style={styles.hint}>עדיין אין חלקים ברשימה. המנהל יכול להוסיף אותם במערכת.</Text> : catalog.map(category => <View key={category.id}><Text style={styles.category}>{category.name}</Text>{category.parts.map(part => <View key={part.id} style={styles.part}><View><Text style={styles.partName}>{part.name}</Text><Text style={styles.hint}>{part.partNumber ? `${part.partNumber} · ` : ""}{part.unit}</Text></View><View style={styles.counter}><TouchableOpacity onPress={() => changePart(part.id, -1)}><Text style={styles.counterButton}>−</Text></TouchableOpacity><Text>{selected.get(part.id) ?? 0}</Text><TouchableOpacity onPress={() => changePart(part.id, 1)}><Text style={styles.counterButton}>＋</Text></TouchableOpacity></View></View>)}</View>)}</Card>
    <Card><Text style={styles.title}>תמונות או סרטונים</Text><Text style={styles.hint}>לא חובה. עד 50MB לכל קובץ.</Text><Button label="הוספת תמונה או סרטון" variant="secondary" onPress={() => void addMedia()}/>{media.map(m => <View key={m.uri} style={styles.media}><Text>{m.type === "video" ? "סרטון" : "תמונה"}: {m.name}</Text>{m.type === "image" ? <Image source={{ uri: m.uri }} style={styles.thumbnail}/> : null}</View>)}</Card>
    <Card><Text style={styles.title}>אישור לקוח וחתימה</Text><TextInput value={representative} onChangeText={setRepresentative} style={styles.shortInput} placeholder="שם נציג הלקוח (לא חובה)" placeholderTextColor={colors.textMuted}/><TextInput value={role} onChangeText={setRole} style={styles.shortInput} placeholder="תפקיד / הערה (לא חובה)" placeholderTextColor={colors.textMuted}/><Text style={styles.hint}>חתום באצבע בתוך המסגרת. החתימה אופציונלית.</Text><View style={styles.signature} onTouchStart={point} onTouchMove={point} onTouchEnd={finishStroke}>{signature.flatMap((stroke, s) => stroke.map((p, i) => <View key={`${s}-${i}`} style={[styles.dot, { left: p[0], top: p[1] }]}/>))}</View><Button label="ניקוי חתימה" variant="secondary" onPress={() => setSignature([])}/></Card>
    <Button label={`שמירת דוח ${report.reportNumber}`} loading={busy} onPress={() => void save()}/><Text style={styles.hint}>הדוח והכמויות ניתנים לעריכה גם לאחר השמירה על ידי מנהל השירות.</Text>
  </ScrollView>;
}
const styles = StyleSheet.create({ content:{padding:spacing.lg,gap:spacing.md,paddingBottom:spacing.xl*2}, center:{flex:1,alignItems:"center",justifyContent:"center",backgroundColor:colors.bg}, title:{fontSize:18,fontWeight:"800",color:colors.text,marginBottom:8,textAlign:"right",writingDirection:"rtl"}, input:{minHeight:130,borderWidth:1,borderColor:colors.border,borderRadius:10,padding:12,color:colors.text,textAlign:"right",writingDirection:"rtl",textAlignVertical:"top"}, shortInput:{borderWidth:1,borderColor:colors.border,borderRadius:10,padding:12,color:colors.text,textAlign:"right",writingDirection:"rtl",marginTop:8}, hint:{color:colors.textMuted,fontSize:13,marginBottom:10,textAlign:"right",writingDirection:"rtl"}, error:{color:colors.error,fontWeight:"700",textAlign:"right",writingDirection:"rtl"}, category:{fontWeight:"800",color:colors.primary,marginTop:10,textAlign:"right",writingDirection:"rtl"}, part:{flexDirection:"row-reverse",justifyContent:"space-between",alignItems:"center",paddingVertical:9,borderBottomWidth:1,borderBottomColor:colors.border}, partName:{color:colors.text,fontWeight:"600",textAlign:"right",writingDirection:"rtl"}, counter:{flexDirection:"row",alignItems:"center",gap:14}, counterButton:{fontSize:24,color:colors.primary,fontWeight:"800"}, media:{marginTop:10}, thumbnail:{width:90,height:70,borderRadius:8,marginTop:4,alignSelf:"flex-end"}, signature:{height:170,borderWidth:1,borderColor:colors.border,borderRadius:10,marginVertical:10,overflow:"hidden",position:"relative"}, dot:{width:4,height:4,borderRadius:2,backgroundColor:colors.text,position:"absolute"} });
