import type { Locale } from "../i18n/types.js";
import { formatDateTime } from "../i18n/format.js";
import type { MonthlyAttendanceReport } from "./attendance-api.js";

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

function hours(minutes: number): string {
  return `${Math.floor(minutes / 60)}:${String(minutes % 60).padStart(2, "0")}`;
}

const copy = {
  he: {
    title: "דוח נוכחות חודשי",
    month: "חודש",
    status: "מצב",
    locked: "נעול לשכר",
    open: "פתוח לעריכה",
    employees: "עובדים",
    workDays: "ימי עבודה",
    totalNet: "סה״כ שעות נטו",
    date: "תאריך ושעת התחלה",
    end: "שעת סיום",
    gross: "ברוטו",
    breaks: "הפסקות",
    net: "נטו",
    approval: "אישור",
    approved: "מאושר",
    pending: "ממתין",
    active: "פעיל",
    generated: "הופק באמצעות AMAROK ONE",
  },
  en: {
    title: "Monthly attendance report",
    month: "Month",
    status: "Status",
    locked: "Locked for payroll",
    open: "Open for editing",
    employees: "Employees",
    workDays: "Work days",
    totalNet: "Total net hours",
    date: "Start date and time",
    end: "End time",
    gross: "Gross",
    breaks: "Breaks",
    net: "Net",
    approval: "Approval",
    approved: "Approved",
    pending: "Pending",
    active: "Active",
    generated: "Generated by AMAROK ONE",
  },
} as const;

export function buildAttendancePrintHtml(
  report: MonthlyAttendanceReport,
  organizationName: string,
  locale: Locale,
): string {
  const labels = copy[locale];
  const direction = locale === "he" ? "rtl" : "ltr";
  const employeeSections = report.employees
    .map(
      (employee) => `
    <section class="employee">
      <h2>${escapeHtml(employee.displayName)} <small>${escapeHtml(employee.email)}</small></h2>
      <table><thead><tr><th>${labels.date}</th><th>${labels.end}</th><th>${labels.gross}</th>
      <th>${labels.breaks}</th><th>${labels.net}</th><th>${labels.approval}</th></tr></thead>
      <tbody>${employee.days
        .map(
          (day) => `<tr>
        <td>${escapeHtml(formatDateTime(day.startedAt, locale))}</td>
        <td>${day.endedAt ? escapeHtml(formatDateTime(day.endedAt, locale)) : labels.active}</td>
        <td>${hours(day.grossMinutes)}</td><td>${hours(day.breakMinutes)}</td>
        <td><strong>${hours(day.netMinutes)}</strong></td>
        <td>${day.reviewStatus === "APPROVED" ? labels.approved : labels.pending}</td>
      </tr>`,
        )
        .join("")}</tbody></table>
      <p class="employee-total">${labels.workDays}: ${employee.workDays} | ${labels.totalNet}: ${hours(employee.netMinutes)}</p>
    </section>`,
    )
    .join("");

  return `<!doctype html><html lang="${locale}" dir="${direction}"><head><meta charset="utf-8" />
<title>${escapeHtml(organizationName)} - ${labels.title} ${report.month}</title><style>
@page { size: A4; margin: 14mm; } * { box-sizing: border-box; }
body { margin: 0; color: #172033; font-family: Arial, "Noto Sans Hebrew", sans-serif; font-size: 10.5pt; }
header { border-bottom: 3px solid #e9a317; padding-bottom: 12px; margin-bottom: 18px; }
.brand { color: #e09a0d; font-size: 10pt; font-weight: 800; letter-spacing: 1.5px; }
h1 { margin: 4px 0; font-size: 23pt; } header p { margin: 3px 0; color: #566074; }
.summary { display: grid; grid-template-columns: repeat(3, 1fr); gap: 10px; margin-bottom: 18px; }
.card { border: 1px solid #d8dde7; border-radius: 7px; padding: 10px; }
.card span { display: block; color: #687286; font-size: 9pt; } .card strong { display: block; margin-top: 3px; font-size: 16pt; }
.employee { break-inside: avoid; margin: 0 0 18px; } h2 { margin: 0 0 7px; font-size: 13pt; }
h2 small { color: #687286; font-size: 9pt; font-weight: 400; } table { width: 100%; border-collapse: collapse; font-size: 8.5pt; }
th { background: #172033; color: #fff; text-align: start; padding: 7px 6px; }
td { border-bottom: 1px solid #d8dde7; padding: 6px; vertical-align: top; } tr:nth-child(even) td { background: #f6f7f9; }
.employee-total { margin: 6px 0 0; font-weight: 700; text-align: end; }
footer { position: fixed; bottom: -8mm; width: 100%; color: #7a8394; font-size: 8pt; text-align: center; }
</style></head><body><header><div class="brand">AMAROK ONE</div><h1>${labels.title}</h1>
<p><strong>${escapeHtml(organizationName)}</strong></p>
<p>${labels.month}: ${report.month} | ${labels.status}: ${report.locked ? labels.locked : labels.open}</p></header>
<div class="summary"><div class="card"><span>${labels.employees}</span><strong>${report.employeeCount}</strong></div>
<div class="card"><span>${labels.workDays}</span><strong>${report.totalWorkDays}</strong></div>
<div class="card"><span>${labels.totalNet}</span><strong>${hours(report.totalNetMinutes)}</strong></div></div>
${employeeSections}<footer>${labels.generated}</footer></body></html>`;
}

export function printAttendanceReport(
  report: MonthlyAttendanceReport,
  organizationName: string,
  locale: Locale,
): boolean {
  const printWindow = window.open("", "_blank");
  if (!printWindow) return false;
  printWindow.opener = null;
  printWindow.document.open();
  printWindow.document.write(buildAttendancePrintHtml(report, organizationName, locale));
  printWindow.document.close();
  printWindow.focus();
  window.setTimeout(() => printWindow.print(), 250);
  return true;
}
